name: size_checker
description: Find the cost of adding an Android Package.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  aqueduct: 4.0.0-b1
  process_run: ^0.11.0+2
  uuid: ^2.2.2
  io: ^0.3.4
  worker_manager: ^3.0.3
#dependency_overrides:
#  postgres: 2.1.1

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^2.0.0-b1